#!/bin/bash

CURDIR=`pwd`

TILDA=".Xresources .xinitrc .bashrc .vimrc .icons"
CONFIG="i3 i3blocks zathura ncmpcpp mopidy bspwm sxhkd"
LOCAL="bin"

printhelp()
{
  echo -e "$0 usage:"
  echo -e "\t $0 -i \t put all neccessary files to destinations"
  echo -e "\t $0 -e \t install external files and scripts"
  echo -e "\t $0 -c \t remove existing dotfiles"
}

if [[ "$1" =~ ^("-c"|"-i")$ ]]; then
  for f in $TILDA ; do
    [ -L ~/$f ] && rm -r ~/$f && echo "removed $f"
    [ "$1" == "-i" ] && ln -s $CURDIR/$f ~/$f && echo "linked $f"
  done
  
  for f in $CONFIG ; do
    [ -L ~/.config/$f ] && rm -r ~/.config/$f && echo "removed $f"
    [ "$1" == "-i" ] && ln -s $CURDIR/$f ~/.config/$f && echo "linked $f"
  done
  
  for f in $LOCAL ; do
    [ -L ~/.local/$f ] && rm -r ~/.local/$f && echo "removed $f"
    [ "$1" == "-i" ] && ln -s $CURDIR/$f ~/.local/$f && echo "linked $f"
  done
elif [[ "$1" =~ ^("-e")$ ]]; then
  [ ! -d "~/.urxvt/ext" ] && mkdir -p ~/.urxvt/ext 
  wget -nv https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size -P ~/.urxvt/ext
  echo "installed urxvt extension"
  
  [ ! -d "~/.themes" ] && mkdir -p ~/.themes
  [ ! -d "~/.icons" ] && mkdir -p ~/.icons 
  git clone https://github.com/TheGreatMcPain/gruvbox-material-gtk.git
  mv gruvbox-material-gtk/icons/* ~/.icons
  mv gruvbox-material-gtk/themes/* ~/.themes
  rm -rf gruvbox-material-gtk
  echo "installed gruvbox gtk theme and icons"
else
  printhelp
fi
exit 0
