#!/bin/bash

CURDIR=`pwd`

TILDA=".Xresources .xinitrc .bashrc .vimrc .icons"
CONFIG="i3 i3blocks zathura ncmpcpp mopidy bspwm sxhkd"

printhelp()
{
  echo -e "$0 usage:"
  echo -e "\t $0 -i \t put all neccessary files to destinations"
  echo -e "\t $0 -e \t install external files and scripts"
  echo -e "\t $0 -c \t remove existing dotfiles"
}

if [[ "$1" =~ ^("-c"|"-i")$ ]]; then
  for f in $TILDA ; do
    [ -L ~/$f ] && rm -r ~/$f && echo "removed $f"
    [ "$1" == "-i" ] && ln -s $CURDIR/$f ~/$f && echo "linked $f"
  done
  
  for f in $CONFIG ; do
    [ -L ~/.config/$f ] && rm -r ~/.config/$f && echo "removed $f"
    [ "$1" == "-i" ] && ln -s $CURDIR/$f ~/.config/$f && echo "linked $f"
  done
  
elif [[ "$1" =~ ^("-e")$ ]]; then
  [ ! -d "~/.urxvt/ext" ] && mkdir -p ~/.urxvt/ext 
  wget -nv https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size -P ~/.urxvt/ext
  echo "installed urxvt extension"
  
  [ ! -d "~/.vim/colors" ] && mkdir -p ~/.vim/colors
  wget -nv https://raw.githubusercontent.com/srcery-colors/srcery-vim/master/colors/srcery.vim -P ~/.vim/colors
  echo "installed srcery vim theme"
else
  printhelp
fi
exit 0
