#!/bin/bash

PIDS=$(pgrep umess; pgrep ubatloop)
[ ! -z "$PIDS" ] && kill $PIDS
ubatloop &

MAINMON="eDP-1"
bspc monitor ${MAINMON} -d terminal gui browser
for mon in $(active_mons); do
  [ $mon = $MAINMON ] && continue
  bspc monitor ${mon} -d I:$mon II:$mon III:$mon IV:$mon
done

bspc rule -a TelegramDesktop desktop=gui
bspc rule -a Skype desktop=gui
bspc rule -a Zathura state=tiled

bspc config honor_size_hints false
bspc config border_width 4
bspc config window_gap 0
bspc config focused_border_color "#689d6a"
bspc config active_border_color  "#665c54"
bspc config normal_border_color  "#504945"

bspc config focus_follows_pointer true
