#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

for mon_dims in `~/.local/bin/active_mons`; do
    mon=${mon_dims%%:*}
    dims=${mon_dims#*:}
    if [ -z "$prev_mon" ]; then
        xrandr --output $mon --primary --mode $dims
    else
        xrandr --output $mon --right-of $prev_mon --mode 1920x1080
    fi
    bspc monitor $mon -d I II III
    prev_mon=$mon
done

bspc config focus_follows_pointer true
bspc config border_width 2
bspc config window_gap 5

bspc rule -a Matplotlib state=floating
