#!/bin/bash

bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

PIDS=$(pgrep umess; pgrep ubatloop)
[ ! -z "$PIDS" ] && kill $PIDS
ubatloop &

MAINMON=eDP1
xrandr --output $MAINMON --primary --mode 1920x1080 --rotate normal 

ACTIVEMONS=$(active_mons)
PREVMON=$MAINMON
for MON in $(active_mons); do
  if [[ $MON == $MAINMON ]]; then
    bspc monitor ${MAINMON} -d terminal gui browser
    continue
  fi
  xrandr --output $MON --mode 1920x1080 --rotate normal --right-of $PREVMON
  bspc monitor $MON -d I:$MON II:$MON III:$MON IV:$MON
  PREVMON=$MON
done

bspc rule -a TelegramDesktop desktop=gui
bspc rule -a Skype desktop=gui
bspc rule -a Zathura state=tiled

bspc config honor_size_hints false
bspc config border_width 3
bspc config window_gap 0
bspc config focused_border_color "#fce8c3"
bspc config active_border_color  "#baa67f"
bspc config normal_border_color  "#918175"

