#! /bin/sh

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Enable each active monitor from left to right
for mon_dims in `~/.local/bin/active_mons`; do
    mon=${mon_dims%%:*}
    dims=${mon_dims#*:}
    if [ -z "$prev_mon" ]; then
        xrandr --output $mon --primary --mode $dims
    else
        xrandr --output $mon --right-of $prev_mon --mode 1920x1080
    fi

    bspc monitor $mon -d I II III
    prev_mon=$mon
done

# Some self-explanatory stuff
bspc config border_width 4
bspc config window_gap 0
bspc config focus_follows_pointer true
bspc config honor_size_hints false

bspc config normal_border_color \#928374
bspc config active_border_color \#928374
bspc config focused_border_color \#a89984
