#!/bin/bash

# Colors
reset="$(tput sgr0)"
lc="${reset}$(tput bold)$(tput setaf 6)" 
logo="${reset}$(tput bold)$(tput setaf 1)" 
palette="$(printf '\e[%sm  ' {40..47} 0; echo)"

# Items
. /etc/os-release
osname=$NAME
osver=$VERSION_ID
wmname="$(xprop -id $(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}') -notype -f _NET_WM_NAME 8t | grep "WM_NAME" | cut -f2 -d \")"
uptime="$(uptime -p | sed 's/up //g; s/,//g; s/ weeks\?/w/g; s/ days\?/d/g; s/ hours\?/h/g; s/ minutes\?/m/g')"
packages="$(dpkg -l | grep -c '^ii')"
kernel="$(uname -sr)"

tput clear
cat << EOF 
${logo}    ,---._ 
${logo}  /\`  __  \\   ${lc}os${reset}     $osname $osver
${logo} |   /    |   ${lc}kernel${reset} $kernel
${logo} |   \`.__.\`   ${lc}uptime${reset} $uptime  
${logo}  \\           ${lc}pkgs${reset}   $packages 
${logo}   \`-,_     

EOF

