#!/bin/bash
# Some basic umess notifications.
# Author: Vasily Negrebetskiy

FONT="Iosevka:size=14"
FG="#000000"
BG="#d0d0d0"
TIME=2

PIDS=$(pgrep umess)
[ ! -z "$PIDS" ] && kill $PIDS

STRING=""
case $1 in
  -t|--time)
    STRING=$(date '+%Y-%m-%d %H:%M')
    ;;
  -d|--desktop)
    STRING=$(xprop -root | perl -ne "/^_NET_CURRENT_DESKTOP\(CARDINAL\) = (\d+)/ && print 'Desktop: '.(\$1+1)")
    ;;
  -b|--battery)
    STRING=$(acpi | perl -ne "/^Battery \d+: (.+)/ && print \$1")
    ;;
  -l|--language)
    STRING=$(setxkbmap -query | perl -ne "/^layout:\s*([A-Za-z]+)$/ && print \$1")
    ;;
  -bl|--backlight)
    STRING=$(brightnessctl | grep -oP "\d+%")
    ;;
  -v|--volume)
    STRING=$(amixer get Master | perl -nle "/(\d+\%).*(\bon\b|\boff\b)/ && print \$2.' '.\$1") 
    ;;
esac

(echo $STRING; sleep $TIME) | umess -b -f $FONT -F $FG -B $BG 
