#!/bin/bash
# Some basic umess notifications.
# Author: Vasily Negrebetskiy

FONT="Iosevka:size=16"
FG="#1c1b19"
BG="#98bc37"
TIME=4

PIDS=$(pgrep umess)
[ ! -z "$PIDS" ] && kill $PIDS

STRING=""
case $1 in
  -t|--time)
    STRING=$(date '+%Y-%m-%d %H:%M')
    ;;
  -d|--desktop)
    STRING=$(xprop -root | perl -ne "/^_NET_CURRENT_DESKTOP\(CARDINAL\) = (\d+)/ && print 'Desktop: '.(\$1+1)")
    ;;
  -b|--battery)
    STRING=$(acpi | perl -ne "/^Battery \d+: (.+)/ && print \$1")
    ;;
  -l|--language)
    STRING=$(setxkbmap -query | perl -ne "/^layout:\s*([A-Za-z]+)$/ && print \$1")
    ;;
  -bl|--backlight)
    STRING=Backlight:$(brightnessctl | grep -oP "\d+%")
    ;;
  -v|--volume)
    STRING=Volume:$(pamixer --get-volume)%
    ;;
esac

(echo $STRING; sleep $TIME) | umess -b -f $FONT -F $FG -B $BG 
