#!/bin/bash
# Some basic umess notifications.
# Author: Vasily Negrebetskiy

FONT="Iosevka Term Extended:size=14"
FG="#1C1B19"
BG="#FBB829"
TIME=4

PIDS=$(pgrep umess)
[ ! -z "$PIDS" ] && kill $PIDS

STRING=""
case $1 in
  -t|--time)
    STRING=$(date '+%Y-%m-%d %H:%M')
    ;;
  -d|--desktop)
    #STRING=$(xprop -root | perl -ne "/^_NET_CURRENT_DESKTOP\(CARDINAL\) = (\d+)/ && print 'Desktop: '.(\$1+1)")
    STRING="Desktop: "$(bspc query -M -d focused --names)": "$(bspc query -D -d focused --names)
    ;;
  -b|--battery)
    STRING="Battery: "$(acpi | perl -ne "/^Battery \d+: (.+)/ && print \$1")
    ;;
  -l|--layout)
    STRING="Layout: "$(setxkbmap -query | perl -ne "/^layout:\s*([A-Za-z]+)$/ && print \$1")
    ;;
  -bl|--backlight)
    STRING="Backlight: "$(brightnessctl | grep -oP "\d+%")
    ;;
  -v|--volume)
    STRING="Volume: "$(pamixer --get-volume)%
    ;;
esac

(echo $STRING; sleep $TIME) | umess -b -f "$FONT" -F $FG -B $BG $2 
